### PR TITLE
fix: run command fail on windows

### LINKED ISSUE #1: Failed to run on windows platform
Thank to build this tool. It's helpful. 

But I found a problem when I try to generate git commit, this is the error message.

```bash
Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT
```

I have only tested on the Win platform， and I think this is because of the problem with the `cwd` value.

```ts
exec(cmd, {
-   cwd: repo.rootUri.path,    
+   cwd: repo.rootUri.fsPath,
}, (err, stdout, stderr) => {
```

reference:
https://github.com/Microsoft/vscode/issues/28271#issuecomment-308592929
https://github.com/microsoft/vscode/issues/168758#issuecomment-1381295248

### PR DESCRIPTION
**Pull request by zcf0508**
FIX: https://github.com/pwwang/vscode-gptcommit/issues/1

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -4,6 +4,7 @@ import { tmpdir } from 'os';
 import { existsSync, readFileSync, unlinkSync, writeFileSync } from 'fs';
 import { exec, execSync } from 'child_process';
 import { GitExtension, Repository } from './@types/git';
+import * as path from 'path'
```
Comment (pwwang) [inline src/utils.ts]: All look good. Could you put this on the second line?

Comment (zcf0508) [reply src/utils.ts]: 👌 Done.

**Comment by pwwang** [comment]
Thanks!
